name: Build, Publish Docker Image and Deploy Frontend
run-name: Build, Publish Docker Image and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/embarque-ja-frontend:latest

      - name: SSH to VPS and deploy frontend container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop frontend || true
            sudo docker rm frontend || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/embarque-ja-frontend:latest

            # Rodar o contêiner do frontend com a nova imagem
            sudo docker run -d -p 5173:5173 --name frontend ${{ secrets.DOCKER_USERNAME }}/embarque-ja-frontend:latest
